### ISSUE TITLE
[Not a bug] Thank you

### ISSUE THREAD

**Issue by Overc1ocker** [KelvinNarrowRiver/Simple-Countdown-Timer-For-OBS#2]
Thanks for this excellent timer! Got it working perfectly with my setup! 

In addition, I'd like to thank you for making the code super readable. There were a few changes I made for my own use case, but thanks to your easy to read code, it took me only 20 minutes to make all the changes!

This is a great timer and it's working well with OBS 29.0.2 on Linux

**Comment by KelvinNarrowRiver** [comment]
Very Good Thanks.

Never tested it with Linux. Glad it works.

I use Visual Studio Code and a plugin called prettier formats the code on each save that indents everything correctly. I make it easy to follow so Its easy to change at a later date for myself but anyone can benefit.

I’m going to update it later and I was wondering what changes you made as maybe I would like to replicate them.


From: ***@***.***>
Sent: Thursday, 4 May 2023 7:22 PM
To: ***@***.***>
Cc: ***@***.***>
Subject: [KelvinNarrowRiver/Simple-Countdown-Timer-For-OBS] [Not a bug] Thank you (Issue #2)


Thanks for this excellent timer! Got it working perfectly with my setup!

In addition, I'd like to thank you for making the code super readable. There were a few changes I made for my own use case, but thanks to your easy to read code, it took me only 20 minutes to make all the changes!

This is a great timer and it's working well with OBS 29.0.2 on Linux
