### ISSUE TITLE
the timer display does not appear

### ISSUE THREAD

**Issue by LordDOnCrack** [KelvinNarrowRiver/Simple-Countdown-Timer-For-OBS#3]
I really like this countdown but I found a problem. when I add the HTML browser to OBS, the timer is not detected. The dock works normally, but when I tested the dock, the timer display opened in the browser didn't change, it only showed the number 00 and the display on the obs wasn't even visible. please help

**Comment by KelvinNarrowRiver** [comment]
I'm not sure why It"s doing that. When It's installed correctly it should work. I'm not live streaming ATM but it's still working for me just a sec ago. Sometimes Updates to OBS change things. I'm using OBS version 29.1.3. On WIN  11. If the version of OBS has changed I will delete OBS redownload everything and reinstall it again. If the dock is working correctly any changes should display almost instantly on the browser source in OBS. Try typing 1 into the minutes and press return on the dock and it should show the change on the dock and bowser instantly . If no there is no change to the OBS browser source then the dock is not talking with each other. Try deleting both and reinstalling. by default the browser will show white 00 with black border so it will show in all backgrounds. All changes are saved as well as resets. If there's nothing showing in OBS then there is usually something wrong with the install. only copy the URL of the locally opened file to OBS's browser source and change the screen size to suit. do not tick the local file button in OBS.

**Comment by KelvinNarrowRiver** [comment]
Did you get it going?
