### ISSUE TITLE
Google Fonts Not Importing

### ISSUE THREAD

**Issue by MKX1010** [KelvinNarrowRiver/Simple-Countdown-Timer-For-OBS#4]
Hey there -- I made this account on the prompt of encountering this bug, so please do forgive any faux pas with any Github etiquette.

Introductions aside, I just attempted to use a given font for the counter, per the given instructions. Regrettably, this didn't work; it went to the default placeholder font. In particular, it was Jacquard 12 Charted ( https://fonts.google.com/share?selection.family=Jacquard+12+Charted ). I believe it might be because the import code doesn't specify its parameters, unlike Nunito & others I've experimented with.

**Comment by KelvinNarrowRiver** [comment]
Hi MKX1010,   I haven't looked at the timer code or used it for quite a while. I'll get it working again shortly and try and load that font and see how it goes for me.

**Comment by MKX1010** [comment]
Ah, no worries. Just getting into streaming, I caught wind of the brilliant little thing by recommendation. I'd say your work is most certainly worthy, & look forward to any updates you make.

**Comment by KelvinNarrowRiver** [comment]
Thanks for letting me know. I have installed the latest OBS and using a fresh download of the simple countdown timer. all seems to be working ok. But that font you used and others are not working as they should. Some are working fine though. The main font URL works but I think Google has changed there syntax of some things. I will have to look into it a little deeper. I Think font-families that are San-serif and 400 in weight will work. I will have to do a sort of complete overhaul of the font system so all google fonts just work. This will take some time though but an update to the timer will be good.

**Comment by MKX1010** [comment]
For sure -- & thank you for keeping up with it.

Yeah, given that some worked & others didn't, with my layman's
understanding, I figured it had to be something like that. I'll be
positively pleased to see the turnout, & look forward to the progress. Let
me know if you need a guinea pig for testing at any point.

**Comment by KelvinNarrowRiver** [comment]
Yea No Worries. I've got that font working now. The Font Family name is the only thing I've inputted different. I'm still going to overhaul the main dock and do a new vid. The URL for the Font are the same. For your font.
URL :  https://fonts.googleapis.com/css2?family=Jacquard+12+Charted&display=swap
Font Family :   "Jacquard 12 Charted", system-ui

<img width="505" alt="Screenshot 2024-05-01 232734" src="https://github.com/KelvinNarrowRiver/Simple-Countdown-Timer-For-OBS/assets/104570886/4132619e-273d-4bcd-a4ba-64ab54c9c971">

**Comment by MKX1010** [comment]
Ayy! Mighty big ups from me, for that! And just in time, as I discarded the built-in timer. 
Between the workaround you've just shown & the coming updates, this is a stellar development. Shall I go ahead & close the thread?

**Comment by KelvinNarrowRiver** [comment]
Awesome glad your problem is fixed and you have prompted me to look into the font input/change process. Yep go ahead and close this thread if you want to. Most google Fonts should work now with the full Font Family name being imputed. With no code change. The main change to the font system in the code will be the addition of the Font-Weight property ( 400 is the Default ) and the Font-Styles property ( normal is the Default with Italic being the main other option ). Some fonts have variable Weights and some fonts have many fixed weights. I think at the moment these properties can be only changed by the URL. Anyway Ill look into this further. Is there any changes you would like?

**Comment by MKX1010** [comment]
O'course; &, that does sound plausible.

If I were given the opportunity to request any given feature set, it would be an expanded effects list for the text; particularly, that shadow effect is really nice. Given my stream's overall aesthetic, I wish that I could go well above the limit of 40. And if it were at all possible, something akin to a gradient or feathering effect for the text would be impossible to beat.

**Comment by KelvinNarrowRiver** [comment]
Just Letting you know that I am working on an update. Gradients are defiantly coming with a better stroke or shadow.
